-- TRIGGERS
DELIMITER $$

CREATE TRIGGER TR01_ATFB005
AFTER INSERT ON ATFTB005_VENDA_VEICULO
FOR EACH ROW
BEGIN
    UPDATE ATFTB003_VEICULO
    SET IC_STATUS = 'V'
    WHERE ID_VEICULO = NEW.ID_VEICULO AND IC_STATUS <> 'V';
END $$

DELIMITER ;


DELIMITER $$

CREATE TRIGGER TR02_ATFB005
AFTER DELETE ON ATFTB005_VENDA_VEICULO
FOR EACH ROW
BEGIN
    DECLARE v_count INT;

    SELECT COUNT(*) INTO v_count
    FROM ATFTB005_VENDA_VEICULO
    WHERE ID_VEICULO = OLD.ID_VEICULO;

    IF v_count = 0 THEN
        UPDATE ATFTB003_VEICULO
        SET IC_STATUS = 'D'
        WHERE ID_VEICULO = OLD.ID_VEICULO;
    END IF;
END $$

DELIMITER ;
