DROP DATABASE IF EXISTS DB_CAMPEONATO_BRASILEIRO;
CREATE DATABASE DB_CAMPEONATO_BRASILEIRO;
USE DB_CAMPEONATO_BRASILEIRO;

-- ==================== Tabela Estadio ======================
CREATE TABLE SNITB001_ESTADIO (
   ID_ESTADIO  INT NOT NULL AUTO_INCREMENT, -- Identificador Sequencial do estadio
   NO_ESTADIO  VARCHAR(100) NOT NULL, -- Nome do estádio
   ED_ESTADIO  VARCHAR(200) NOT NULL, -- Endereço completo do estádio
   QT_CAPACIDADE  INT NOT NULL, -- Capacidade total do estádio
  CONSTRAINT PK_SNITB001 PRIMARY KEY ( ID_ESTADIO ), 
  CONSTRAINT UK01_SNITB001 UNIQUE ( NO_ESTADIO )
  );

-- ==================== Tabela Time ======================
CREATE TABLE SNITB002_TIME  (
   ID_TIME  INT NOT NULL AUTO_INCREMENT, -- Identificador único sequencial do time
   NO_COMPLETO_TIME VARCHAR(150) NOT NULL, -- Nome completo do time
   NO_TIME  VARCHAR(50) NOT NULL, -- Nome comum do time
   SG_TIME CHAR(3) NOT NULL, -- Sigla do time
   NO_CIDADE  VARCHAR(150) NOT NULL, -- Nome da cidade
   NO_ESTADO  VARCHAR(150) NOT NULL, -- Nome do estado
   ID_ESTADIO  INT NOT NULL, -- FK Estadio
  CONSTRAINT PK_SNITB002 PRIMARY KEY ( ID_TIME ),
  CONSTRAINT UK01_SNITB002 UNIQUE ( NO_TIME ),
  CONSTRAINT FK01_SNITB001_SNITB002 FOREIGN KEY ( ID_ESTADIO )
    REFERENCES SNITB001_ESTADIO ( ID_ESTADIO )
    );

-- ==================== Tabela Partida ======================
CREATE TABLE SNITB004_PARTIDA  (
   ID_PARTIDA  INT NOT NULL AUTO_INCREMENT, -- Identificador unico sequencial da partida
   NR_RODADA_CAMPEONATO  INT NOT NULL, -- Numero da rodada
   DH_PARTIDA  DATETIME NOT NULL, -- Data e hora da partida
   QT_GOL_MANDANTE NUMERIC(1) NULL, -- Quantidade de gols do time mandante
   QT_GOL_VISITANTE NUMERIC(1) NULL, -- Quantidade de gols do time visitante
   ID_TIME_MANDANTE  INT NOT NULL, -- Fk do time
   ID_TIME_VISITANTE  INT NOT NULL, -- FK do time
   ID_ESTADIO  INT NOT NULL, -- FK do estadio
  CONSTRAINT PK_SNITB004 PRIMARY KEY ( ID_PARTIDA ),
  CONSTRAINT  FK01_SNITB001_SNITB004 FOREIGN KEY ( ID_ESTADIO )
    REFERENCES  SNITB001_ESTADIO ( ID_ESTADIO ),
  CONSTRAINT  FK02_SNITB002_SNITB004 FOREIGN KEY ( ID_TIME_MANDANTE )
    REFERENCES SNITB002_TIME ( ID_TIME ),
  CONSTRAINT  FK03_SNITB002_SNITB004 FOREIGN KEY ( ID_TIME_VISITANTE )
    REFERENCES SNITB002_TIME ( ID_TIME )
    );

-- ==================== Tabela Jogador ======================
CREATE TABLE SNITB003_JOGADOR  (
	ID_JOGADOR  INT NOT NULL AUTO_INCREMENT, -- Identificador unico sequencial do jogador
	NO_JOGADOR  VARCHAR(100) NOT NULL, -- Nome do jogador
	NR_CAMISA  INT NULL, -- Numero da camisa
	DT_NASCIMENTO  DATE NULL, -- Data de nascimento
	NO_POSICAO  VARCHAR(50) NULL, -- Nome da posicao do jogador
	ID_TIME  INT NOT NULL, -- FK do time que o jogador atua
  CONSTRAINT PK_SNITB003 PRIMARY KEY ( ID_JOGADOR ),
  CONSTRAINT UK01_SNITB003 UNIQUE ( NO_JOGADOR, ID_TIME, DT_NASCIMENTO ),
  CONSTRAINT  FK01_SNITB002_SNITB003 FOREIGN KEY ( ID_TIME )
    REFERENCES SNITB002_TIME ( ID_TIME )
    );

-- ==================== Tabela Evento ======================
CREATE TABLE SNITB005_EVENTO  (
   ID_EVENTO  INT NOT NULL AUTO_INCREMENT, -- Identificador único sequencial do evento
	NR_MINUTO  INT NOT NULL, -- Minuto em que o evento ocorreu
	DS_EVENTO  VARCHAR(150) NOT NULL, -- Descrição do evento. Ex: (Gol)
	ID_PARTIDA  INT NOT NULL, -- FK da partida
	ID_JOGADOR  INT NOT NULL, -- FK do jogador
  PRIMARY KEY ( ID_EVENTO ),
  CONSTRAINT  FK01_SNITB004_SNITB005 FOREIGN KEY ( ID_PARTIDA )
    REFERENCES SNITB004_PARTIDA  ( ID_PARTIDA ),
  CONSTRAINT  FK02_SNITB003_SNITB005 FOREIGN KEY ( ID_JOGADOR ) 
    REFERENCES  SNITB003_JOGADOR  ( ID_JOGADOR )
    );