USE DB_CAMPEONATO_BRASILEIRO;

DELIMITER $$

CREATE PROCEDURE DB_CAMPEONATO_BRASILEIRO.PRC_RODADA(v_rodada INT)
BEGIN
DROP TEMPORARY TABLE IF EXISTS TB_RODADA;
CREATE TEMPORARY TABLE TB_RODADA AS
	WITH 
		TIME_MANDANTE AS (
			SELECT
				ID_TIME_MANDANTE AS ID_TIME,
				QT_GOL_MANDANTE AS GOLS_MANDANTE,
				QT_GOL_VISITANTE AS GOLS_VISITANTE,
				NR_RODADA_CAMPEONATO  
			FROM SNITB004_PARTIDA
			WHERE NR_RODADA_CAMPEONATO <= v_rodada 
		),
		TIME_VISITANTE AS (
			SELECT
				ID_TIME_VISITANTE AS ID_TIME,
				QT_GOL_MANDANTE AS GOLS_MANDANTE,
				QT_GOL_VISITANTE AS GOLS_VISITANTE,
				NR_RODADA_CAMPEONATO  
			FROM SNITB004_PARTIDA
			WHERE NR_RODADA_CAMPEONATO <= v_rodada 
		),
		RESULTADO AS (
			SELECT
				ID_TIME,
				GOLS_MANDANTE,
				GOLS_VISITANTE,
				CASE 
					WHEN GOLS_MANDANTE > GOLS_VISITANTE THEN 3
					WHEN GOLS_MANDANTE < GOLS_VISITANTE THEN 0
					ELSE 1 
				END AS PONTOS_MANDANTE,
				CASE
					WHEN GOLS_VISITANTE > GOLS_MANDANTE THEN 3 
					WHEN GOLS_VISITANTE < GOLS_MANDANTE THEN 0 
					ELSE 1 
				END AS PONTOS_VISITANTE
			FROM TIME_MANDANTE
			UNION ALL
			SELECT 
				ID_TIME,
				GOLS_VISITANTE,
				GOLS_MANDANTE,
				CASE 
					WHEN GOLS_VISITANTE > GOLS_MANDANTE THEN 3
					WHEN GOLS_VISITANTE < GOLS_MANDANTE THEN 0
					ELSE 1 
				END AS PONTOS_MANDANTE,
				CASE
					WHEN GOLS_VISITANTE < GOLS_MANDANTE THEN 3
					WHEN GOLS_VISITANTE > GOLS_MANDANTE THEN 0
					ELSE 1
				END AS PONTOS_VISITANTE
			FROM TIME_VISITANTE
		),
		TABELA_CLASSIFICACAO AS (
			SELECT
				ID_TIME,
				SUM(PONTOS_MANDANTE) + SUM(PONTOS_VISITANTE) AS PONTOS,
				SUM(GOLS_MANDANTE) - SUM(GOLS_VISITANTE) AS SALDO_GOLS,
				SUM(GOLS_MANDANTE) AS GOLS_MARCADOS
			FROM RESULTADO
			GROUP BY ID_TIME
		)
SELECT
    TC.ID_TIME,
    T.NO_TIME,
    TC.PONTOS,
    TC.SALDO_GOLS,
    TC.GOLS_MARCADOS 
FROM TABELA_CLASSIFICACAO TC
INNER JOIN SNITB002_TIME T ON TC.ID_TIME = T.ID_TIME
ORDER BY TC.PONTOS DESC, TC.SALDO_GOLS DESC, TC.GOLS_MARCADOS DESC;
END $$
DELIMITER ;

CALL DB_CAMPEONATO_BRASILEIRO.PRC_RODADA(12);
SELECT 
	row_number() over() Posição,
    TBR.* 
FROM DB_CAMPEONATO_BRASILEIRO.TB_RODADA TBR;
