SELECT
REPLACE(REPLACE(REPLACE(REPLACE(
'INSERT INTO EVENTO(MINUTO, DESCRICAO, ID_PARTIDA, ID_JOGADOR) VALUES (v1, ''v2'', v3, v4);'
        , 'v1', minuto), 'v2', descricao), 'v3', p.id_partida), 'v4', id_jogador)
FROM EVENTO E
INNER JOIN PARTIDA P ON P.ID_PARTIDA = E.ID_PARTIDA
WHERE RODADA = 38
ORDER BY ID_EVENTO;

DELETE FROM EVENTO
WHERE ID_PARTIDA >= 371;
SET SQL_SAFE_UPDATES = 0;

UPDATE PARTIDA
SET GOL_MANDANTE = NULL,
    GOL_VISITANTE = NULL
WHERE RODADA = 38;

DROP  TRIGGER IF EXISTS DEPOIS_INSERT_EVENTO;
DELIMITER $$
CREATE TRIGGER DEPOIS_INSERT_EVENTO AFTER INSERT
ON EVENTO
FOR EACH ROW
BEGIN
DECLARE IDTIME INT;
       
        IF (SELECT GOL_MANDANTE FROM PARTIDA WHERE ID_PARTIDA = NEW.ID_PARTIDA) IS NULL THEN
UPDATE PARTIDA
            SET GOL_MANDANTE = 0, GOL_VISITANTE = 0
            WHERE ID_PARTIDA  = NEW.ID_PARTIDA;
END IF;
       
        IF NEW.DESCRICAO IN ('Gol (Pênalti)', 'Gol (Gol de campo)', 'Gol (Gol Contra)') THEN
SET IDTIME = (SELECT ID_TIME FROM JOGADOR WHERE ID_JOGADOR = NEW.ID_JOGADOR);
            IF NEW.DESCRICAO = 'Gol (Gol Contra)' THEN
SET IDTIME = (
                SELECT
CASE WHEN ID_MANDANTE = IDTIME
THEN ID_VISITANTE
ELSE ID_MANDANTE
END
                FROM PARTIDA WHERE ID_PARTIDA = NEW.ID_PARTIDA
                );
END IF;
        END IF;
       
        IF IDTIME IS NOT NULL THEN
UPDATE PARTIDA
            SET GOL_MANDANTE = GOL_MANDANTE + 1
            WHERE ID_PARTIDA = NEW.ID_PARTIDA
            AND ID_MANDANTE = IDTIME;
           
            UPDATE PARTIDA SET GOL_VISITANTE = GOL_VISITANTE + 1
            WHERE ID_PARTIDA = NEW.ID_PARTIDA
            AND ID_VISITANTE = IDTIME;
END IF;
END $$
DELIMITER ;