USE DB_PROJETO_RESTAURANTE;

-- Cardapio completo
SELECT NO_PRODUTO, DS_PRODUTO, VL_PRODUTO, QT_ESTOQUE
FROM RSTTB003_PRODUTO
WHERE IC_DISPONIVEL = 'D';

-- Listar todas as comandas abertas
SELECT NR_MESA, NO_CLIENTE, DH_ABERTURA
FROM RSTTB001_COMANDA
WHERE IC_SITUACAO = 'A';

-- Obter o histórico de pedidos realizados em uma comanda
SELECT R.NO_CLIENTE, P.DH_PEDIDO, PR.NO_PRODUTO, PD.QT_PRODUTO, PR.VL_PRODUTO, (PD.QT_PRODUTO * PR.VL_PRODUTO) AS TOTAL_ITEM
FROM RSTTB001_COMANDA R
JOIN RSTTB002_PEDIDO P ON R.ID_COMANDA = P.ID_COMANDA
JOIN RSTTB004_PRODUTO_PEDIDO PD ON P.ID_PEDIDO = PD.ID_PEDIDO
JOIN RSTTB003_PRODUTO PR ON PD.ID_PRODUTO = PR.ID_PRODUTO
WHERE R.ID_COMANDA = 1  
ORDER BY P.DH_PEDIDO DESC;

-- Total gasto por uma comanda
SELECT 
    R.NO_CLIENTE,
    GROUP_CONCAT(PDR.NO_PRODUTO SEPARATOR ', ') AS PRODUTOS_PEDIDOS,
    SUM(PDR.VL_PRODUTO * PD.QT_PRODUTO) AS TOTAL_GASTO
FROM RSTTB001_COMANDA R
INNER JOIN RSTTB002_PEDIDO P ON R.ID_COMANDA = P.ID_COMANDA
INNER JOIN RSTTB004_PRODUTO_PEDIDO PD ON P.ID_PEDIDO = PD.ID_PEDIDO
INNER JOIN RSTTB003_PRODUTO PDR ON PD.ID_PRODUTO = PDR.ID_PRODUTO
WHERE R.ID_COMANDA = 1
GROUP BY R.ID_COMANDA, R.NO_CLIENTE;


-- Identificar qual prato foi o mais pedido e quantas vezes ele foi solicitado.
SELECT PR.NO_PRODUTO, SUM(PD.QT_PRODUTO) AS QTD_PEDIDOS
FROM RSTTB004_PRODUTO_PEDIDO PD
JOIN RSTTB003_PRODUTO PR ON PD.ID_PRODUTO = PR.ID_PRODUTO
GROUP BY PR.NO_PRODUTO
ORDER BY QTD_PEDIDOS DESC
LIMIT 1;
