-- backup de insert dos eventos da rodada 38
insert into evento(minuto,descricao,id_partida,id_jogador) values (25,'Cartão Amarelo',371,371);
insert into evento(minuto,descricao,id_partida,id_jogador) values (45,'Gol (Pênalti)',371,280);
insert into evento(minuto,descricao,id_partida,id_jogador) values (46,'Substituição',371,381);
insert into evento(minuto,descricao,id_partida,id_jogador) values (46,'Substituição',371,287);
insert into evento(minuto,descricao,id_partida,id_jogador) values (54,'Cartão Amarelo',371,269);
insert into evento(minuto,descricao,id_partida,id_jogador) values (64,'Cartão Amarelo',371,282);
insert into evento(minuto,descricao,id_partida,id_jogador) values (67,'Substituição',371,392);
insert into evento(minuto,descricao,id_partida,id_jogador) values (68,'Substituição',371,390);
insert into evento(minuto,descricao,id_partida,id_jogador) values (70,'Substituição',371,273);
insert into evento(minuto,descricao,id_partida,id_jogador) values (79,'Cartão Vermelho',371,385);
insert into evento(minuto,descricao,id_partida,id_jogador) values (79,'Cartão Vermelho',371,287);
insert into evento(minuto,descricao,id_partida,id_jogador) values (83,'Substituição',371,290);
insert into evento(minuto,descricao,id_partida,id_jogador) values (84,'Substituição',371,277);
insert into evento(minuto,descricao,id_partida,id_jogador) values (85,'Substituição',371,268);
insert into evento(minuto,descricao,id_partida,id_jogador) values (88,'Gol (Gol de campo)',371,277);
insert into evento(minuto,descricao,id_partida,id_jogador) values (90,'Cartão Amarelo',371,392);
insert into evento(minuto,descricao,id_partida,id_jogador) values (90,'Gol (Gol de campo)',371,265);
insert into evento(minuto,descricao,id_partida,id_jogador) values (90,'Cartão Amarelo',371,288);
insert into evento(minuto,descricao,id_partida,id_jogador) values (24,'Cartão Amarelo',372,416);
insert into evento(minuto,descricao,id_partida,id_jogador) values (56,'Cartão Amarelo',372,407);
insert into evento(minuto,descricao,id_partida,id_jogador) values (61,'Bola na Trave',372,604);
insert into evento(minuto,descricao,id_partida,id_jogador) values (62,'Substituição',372,673);
insert into evento(minuto,descricao,id_partida,id_jogador) values (63,'Substituição',372,411);
insert into evento(minuto,descricao,id_partida,id_jogador) values (66,'Cartão Amarelo',372,408);
insert into evento(minuto,descricao,id_partida,id_jogador) values (70,'Bola na Trave',372,414);
insert into evento(minuto,descricao,id_partida,id_jogador) values (73,'Pênalti Perdido',372,604);
insert into evento(minuto,descricao,id_partida,id_jogador) values (73,'Gol (Gol de campo)',372,629);
insert into evento(minuto,descricao,id_partida,id_jogador) values (73,'Cartão Amarelo',372,628);
insert into evento(minuto,descricao,id_partida,id_jogador) values (75,'Substituição',372,615);
insert into evento(minuto,descricao,id_partida,id_jogador) values (75,'Substituição',372,633);
insert into evento(minuto,descricao,id_partida,id_jogador) values (78,'Substituição',372,425);
insert into evento(minuto,descricao,id_partida,id_jogador) values (79,'Substituição',372,430);
insert into evento(minuto,descricao,id_partida,id_jogador) values (82,'Substituição',372,624);
insert into evento(minuto,descricao,id_partida,id_jogador) values (87,'Substituição',372,605);
insert into evento(minuto,descricao,id_partida,id_jogador) values (87,'Substituição',372,613);
insert into evento(minuto,descricao,id_partida,id_jogador) values (87,'Substituição',372,435);
insert into evento(minuto,descricao,id_partida,id_jogador) values (90,'Cartão Amarelo',372,617);
insert into evento(minuto,descricao,id_partida,id_jogador) values (90,'Cartão Amarelo',372,624);
insert into evento(minuto,descricao,id_partida,id_jogador) values (22,'Substituição',373,655);
insert into evento(minuto,descricao,id_partida,id_jogador) values (36,'Bola na Trave',373,264);
insert into evento(minuto,descricao,id_partida,id_jogador) values (39,'Cartão Amarelo',373,648);
insert into evento(minuto,descricao,id_partida,id_jogador) values (41,'Gol (Gol de campo)',373,252);
insert into evento(minuto,descricao,id_partida,id_jogador) values (46,'Substituição',373,656);
insert into evento(minuto,descricao,id_partida,id_jogador) values (58,'Gol (Pênalti)',373,260);
insert into evento(minuto,descricao,id_partida,id_jogador) values (60,'Substituição',373,640);
insert into evento(minuto,descricao,id_partida,id_jogador) values (60,'Substituição',373,668);
insert into evento(minuto,descricao,id_partida,id_jogador) values (67,'Substituição',373,256);
insert into evento(minuto,descricao,id_partida,id_jogador) values (67,'Substituição',373,261);
insert into evento(minuto,descricao,id_partida,id_jogador) values (70,'Substituição',373,242);
insert into evento(minuto,descricao,id_partida,id_jogador) values (71,'Substituição',373,253);
insert into evento(minuto,descricao,id_partida,id_jogador) values (74,'Cartão Amarelo',373,256);
insert into evento(minuto,descricao,id_partida,id_jogador) values (76,'Substituição',373,649);
insert into evento(minuto,descricao,id_partida,id_jogador) values (79,'Substituição',373,243);
insert into evento(minuto,descricao,id_partida,id_jogador) values (90,'Cartão Amarelo',373,243);
insert into evento(minuto,descricao,id_partida,id_jogador) values (90,'Cartão Amarelo',373,242);
insert into evento(minuto,descricao,id_partida,id_jogador) values (2,'Bola na Trave',376,472);
insert into evento(minuto,descricao,id_partida,id_jogador) values (7,'Cartão Amarelo',376,489);
insert into evento(minuto,descricao,id_partida,id_jogador) values (37,'Gol (Gol de campo)',376,497);
insert into evento(minuto,descricao,id_partida,id_jogador) values (41,'Cartão Amarelo',376,479);
insert into evento(minuto,descricao,id_partida,id_jogador) values (46,'Substituição',376,39);
insert into evento(minuto,descricao,id_partida,id_jogador) values (54,'Gol anulado (Var)',376,60);
insert into evento(minuto,descricao,id_partida,id_jogador) values (58,'Substituição',376,506);
insert into evento(minuto,descricao,id_partida,id_jogador) values (67,'Substituição',376,40);
insert into evento(minuto,descricao,id_partida,id_jogador) values (67,'Substituição',376,51);
insert into evento(minuto,descricao,id_partida,id_jogador) values (67,'Substituição',376,53);
insert into evento(minuto,descricao,id_partida,id_jogador) values (70,'Substituição',376,45);
insert into evento(minuto,descricao,id_partida,id_jogador) values (75,'Substituição',376,473);
insert into evento(minuto,descricao,id_partida,id_jogador) values (83,'Cartão Amarelo',376,40);
insert into evento(minuto,descricao,id_partida,id_jogador) values (85,'Substituição',376,480);
insert into evento(minuto,descricao,id_partida,id_jogador) values (85,'Cartão Amarelo',376,56);
insert into evento(minuto,descricao,id_partida,id_jogador) values (90,'Cartão Amarelo',376,67);
insert into evento(minuto,descricao,id_partida,id_jogador) values (90,'Cartão Amarelo',376,506);
insert into evento(minuto,descricao,id_partida,id_jogador) values (90,'Cartão Amarelo',376,499);
insert into evento(minuto,descricao,id_partida,id_jogador) values (37,'Gol (Gol de campo)',375,17);
insert into evento(minuto,descricao,id_partida,id_jogador) values (60,'Substituição',375,182);
insert into evento(minuto,descricao,id_partida,id_jogador) values (63,'Gol (Gol de campo)',375,201);
insert into evento(minuto,descricao,id_partida,id_jogador) values (68,'Substituição',375,3);
insert into evento(minuto,descricao,id_partida,id_jogador) values (68,'Substituição',375,31);
insert into evento(minuto,descricao,id_partida,id_jogador) values (81,'Substituição',375,11);
insert into evento(minuto,descricao,id_partida,id_jogador) values (81,'Substituição',375,15);
insert into evento(minuto,descricao,id_partida,id_jogador) values (82,'Substituição',375,195);
insert into evento(minuto,descricao,id_partida,id_jogador) values (82,'Substituição',375,198);
insert into evento(minuto,descricao,id_partida,id_jogador) values (90,'Substituição',375,1);
insert into evento(minuto,descricao,id_partida,id_jogador) values (90,'Substituição',375,825);
insert into evento(minuto,descricao,id_partida,id_jogador) values (90,'Substituição',375,826);
insert into evento(minuto,descricao,id_partida,id_jogador) values (90,'Gol (Gol de campo)',375,19);
insert into evento(minuto,descricao,id_partida,id_jogador) values (7,'Gol (Gol de campo)',378,94);
insert into evento(minuto,descricao,id_partida,id_jogador) values (20,'Gol (Gol de campo)',378,94);
insert into evento(minuto,descricao,id_partida,id_jogador) values (45,'Cartão Amarelo',378,147);
insert into evento(minuto,descricao,id_partida,id_jogador) values (46,'Substituição',378,162);
insert into evento(minuto,descricao,id_partida,id_jogador) values (53,'Gol (Gol de campo)',378,84);
insert into evento(minuto,descricao,id_partida,id_jogador) values (61,'Substituição',378,156);
insert into evento(minuto,descricao,id_partida,id_jogador) values (61,'Substituição',378,671);
insert into evento(minuto,descricao,id_partida,id_jogador) values (62,'Substituição',378,135);
insert into evento(minuto,descricao,id_partida,id_jogador) values (68,'Cartão Amarelo',378,151);
insert into evento(minuto,descricao,id_partida,id_jogador) values (72,'Substituição',378,89);
insert into evento(minuto,descricao,id_partida,id_jogador) values (72,'Substituição',378,73);
insert into evento(minuto,descricao,id_partida,id_jogador) values (73,'Substituição',378,685);
insert into evento(minuto,descricao,id_partida,id_jogador) values (76,'Cartão Amarelo',378,84);
insert into evento(minuto,descricao,id_partida,id_jogador) values (78,'Substituição',378,87);
insert into evento(minuto,descricao,id_partida,id_jogador) values (78,'Substituição',378,93);
insert into evento(minuto,descricao,id_partida,id_jogador) values (87,'Substituição',378,97);
insert into evento(minuto,descricao,id_partida,id_jogador) values (5,'Bola na Trave',379,676);
insert into evento(minuto,descricao,id_partida,id_jogador) values (5,'Bola na Trave',379,590);
insert into evento(minuto,descricao,id_partida,id_jogador) values (17,'Gol (Gol de campo)',379,303);
insert into evento(minuto,descricao,id_partida,id_jogador) values (33,'Gol (Gol de campo)',379,590);
insert into evento(minuto,descricao,id_partida,id_jogador) values (43,'Gol (Gol de campo)',379,303);
insert into evento(minuto,descricao,id_partida,id_jogador) values (46,'Substituição',379,309);
insert into evento(minuto,descricao,id_partida,id_jogador) values (46,'Substituição',379,302);
insert into evento(minuto,descricao,id_partida,id_jogador) values (58,'Substituição',379,301);
insert into evento(minuto,descricao,id_partida,id_jogador) values (62,'Cartão Amarelo',379,309);
insert into evento(minuto,descricao,id_partida,id_jogador) values (65,'Substituição',379,593);
insert into evento(minuto,descricao,id_partida,id_jogador) values (66,'Substituição',379,322);
insert into evento(minuto,descricao,id_partida,id_jogador) values (77,'Gol anulado (Var)',379,322);
insert into evento(minuto,descricao,id_partida,id_jogador) values (78,'Substituição',379,588);
insert into evento(minuto,descricao,id_partida,id_jogador) values (78,'Substituição',379,324);
insert into evento(minuto,descricao,id_partida,id_jogador) values (79,'Substituição',379,827);
insert into evento(minuto,descricao,id_partida,id_jogador) values (84,'Substituição',379,677);
insert into evento(minuto,descricao,id_partida,id_jogador) values (84,'Substituição',379,828);
insert into evento(minuto,descricao,id_partida,id_jogador) values (16,'Gol (Gol de campo)',374,347);
insert into evento(minuto,descricao,id_partida,id_jogador) values (46,'Substituição',374,363);
insert into evento(minuto,descricao,id_partida,id_jogador) values (52,'Cartão Amarelo',374,357);
insert into evento(minuto,descricao,id_partida,id_jogador) values (55,'Substituição',374,119);
insert into evento(minuto,descricao,id_partida,id_jogador) values (55,'Substituição',374,122);
insert into evento(minuto,descricao,id_partida,id_jogador) values (57,'Cartão Amarelo',374,338);
insert into evento(minuto,descricao,id_partida,id_jogador) values (59,'Gol (Gol de campo)',374,103);
insert into evento(minuto,descricao,id_partida,id_jogador) values (61,'Substituição',374,116);
insert into evento(minuto,descricao,id_partida,id_jogador) values (65,'Substituição',374,353);
insert into evento(minuto,descricao,id_partida,id_jogador) values (65,'Substituição',374,361);
insert into evento(minuto,descricao,id_partida,id_jogador) values (74,'Gol (Gol de campo)',374,363);
insert into evento(minuto,descricao,id_partida,id_jogador) values (79,'Gol (Gol de campo)',374,113);
insert into evento(minuto,descricao,id_partida,id_jogador) values (81,'Substituição',374,114);
insert into evento(minuto,descricao,id_partida,id_jogador) values (81,'Substituição',374,125);
insert into evento(minuto,descricao,id_partida,id_jogador) values (90,'Substituição',374,349);
insert into evento(minuto,descricao,id_partida,id_jogador) values (90,'Substituição',374,348);
insert into evento(minuto,descricao,id_partida,id_jogador) values (13,'Gol (Gol de campo)',377,548);
insert into evento(minuto,descricao,id_partida,id_jogador) values (30,'Gol (Gol de campo)',377,573);
insert into evento(minuto,descricao,id_partida,id_jogador) values (39,'Gol (Gol de campo)',377,521);
insert into evento(minuto,descricao,id_partida,id_jogador) values (41,'Cartão Amarelo',377,573);
insert into evento(minuto,descricao,id_partida,id_jogador) values (53,'Cartão Amarelo',377,515);
insert into evento(minuto,descricao,id_partida,id_jogador) values (55,'Gol (Gol de campo)',377,544);
insert into evento(minuto,descricao,id_partida,id_jogador) values (59,'Cartão Amarelo',377,540);
insert into evento(minuto,descricao,id_partida,id_jogador) values (59,'Cartão Amarelo',377,517);
insert into evento(minuto,descricao,id_partida,id_jogador) values (60,'Substituição',377,523);
insert into evento(minuto,descricao,id_partida,id_jogador) values (60,'Substituição',377,528);
insert into evento(minuto,descricao,id_partida,id_jogador) values (61,'Substituição',377,513);
insert into evento(minuto,descricao,id_partida,id_jogador) values (69,'Substituição',377,567);
insert into evento(minuto,descricao,id_partida,id_jogador) values (70,'Gol (Gol de campo)',377,567);
insert into evento(minuto,descricao,id_partida,id_jogador) values (73,'Substituição',377,556);
insert into evento(minuto,descricao,id_partida,id_jogador) values (73,'Substituição',377,564);
insert into evento(minuto,descricao,id_partida,id_jogador) values (73,'Substituição',377,539);
insert into evento(minuto,descricao,id_partida,id_jogador) values (77,'Substituição',377,541);
insert into evento(minuto,descricao,id_partida,id_jogador) values (80,'Substituição',377,549);
insert into evento(minuto,descricao,id_partida,id_jogador) values (80,'Substituição',377,565);
insert into evento(minuto,descricao,id_partida,id_jogador) values (81,'Gol (Gol de campo)',377,569);
insert into evento(minuto,descricao,id_partida,id_jogador) values (89,'Gol anulado (Var)',377,513);
insert into evento(minuto,descricao,id_partida,id_jogador) values (30,'Gol (Gol de campo)',380,686);
insert into evento(minuto,descricao,id_partida,id_jogador) values (36,'Cartão Amarelo',380,461);
insert into evento(minuto,descricao,id_partida,id_jogador) values (40,'Substituição',380,235);
insert into evento(minuto,descricao,id_partida,id_jogador) values (45,'Cartão Vermelho',380,457);
insert into evento(minuto,descricao,id_partida,id_jogador) values (51,'Cartão Amarelo',380,231);
insert into evento(minuto,descricao,id_partida,id_jogador) values (56,'Substituição',380,232);
insert into evento(minuto,descricao,id_partida,id_jogador) values (57,'Cartão Amarelo',380,212);
insert into evento(minuto,descricao,id_partida,id_jogador) values (62,'Substituição',380,441);
insert into evento(minuto,descricao,id_partida,id_jogador) values (62,'Substituição',380,438);
insert into evento(minuto,descricao,id_partida,id_jogador) values (74,'Substituição',380,446);
insert into evento(minuto,descricao,id_partida,id_jogador) values (76,'Cartão Amarelo',380,224);
insert into evento(minuto,descricao,id_partida,id_jogador) values (80,'Cartão Amarelo',380,438);
insert into evento(minuto,descricao,id_partida,id_jogador) values (82,'Substituição',380,447);
insert into evento(minuto,descricao,id_partida,id_jogador) values (82,'Substituição',380,462);
insert into evento(minuto,descricao,id_partida,id_jogador) values (83,'Substituição',380,223);
insert into evento(minuto,descricao,id_partida,id_jogador) values (84,'Substituição',380,226);
insert into evento(minuto,descricao,id_partida,id_jogador) values (90,'Cartão Vermelho (Segundo Cartão Amarelo)',380,212);
insert into evento(minuto,descricao,id_partida,id_jogador) values (90,'Cartão Vermelho (Segundo Cartão Amarelo)',380,438);