-- CALL atualizar_gol_partida('x1',x2,x3,'x4'); -- x5
select 	
    concat('CALL atualizar_gol_partida(''',
    tm.sigla,''',', 
    gol_mandante,',',
    gol_visitante, ',''',
    tv.sigla,'''); -- ',
    p.id_partida) update_partida
from dbcampeonatobr.partida p
inner join dbcampeonatobr.time tm on p.id_mandante = tm.id_time
inner join dbcampeonatobr.time tv on p.id_visitante = tv.id_time
order by p.id_partida;

CALL atualizar_gol_partida('INT',2,1,'BAH'); -- 1
CALL atualizar_gol_partida('CRI',1,1,'JUV'); -- 2
CALL atualizar_gol_partida('FLU',2,2,'RBB'); -- 3
CALL atualizar_gol_partida('SAO',1,2,'FOR'); -- 4
CALL atualizar_gol_partida('VAS',2,1,'GRE'); -- 5
CALL atualizar_gol_partida('COR',0,0,'CAM'); -- 6
CALL atualizar_gol_partida('CAP',4,0,'CUI'); -- 7
CALL atualizar_gol_partida('ACG',1,2,'FLA'); -- 8
CALL atualizar_gol_partida('CRU',3,2,'BOT'); -- 9
CALL atualizar_gol_partida('VIT',0,1,'PAL'); -- 10
CALL atualizar_gol_partida('BAH',2,1,'FLU'); -- 11
CALL atualizar_gol_partida('GRE',2,0,'CAP'); -- 12
CALL atualizar_gol_partida('RBB',2,1,'VAS'); -- 13
CALL atualizar_gol_partida('CAM',1,1,'CRI'); -- 14
CALL atualizar_gol_partida('PAL',0,1,'INT'); -- 15
CALL atualizar_gol_partida('FOR',1,1,'CRU'); -- 16
CALL atualizar_gol_partida('JUV',2,0,'COR'); -- 17
CALL atualizar_gol_partida('FLA',2,1,'SAO'); -- 18
CALL atualizar_gol_partida('BOT',1,0,'ACG'); -- 19
CALL atualizar_gol_partida('CUI',0,0,'VIT'); -- 20
CALL atualizar_gol_partida('FLU',2,1,'VAS'); -- 21
CALL atualizar_gol_partida('GRE',1,0,'CUI'); -- 22
CALL atualizar_gol_partida('RBB',1,0,'COR'); -- 23
CALL atualizar_gol_partida('CAM',3,0,'CRU'); -- 24
CALL atualizar_gol_partida('VIT',2,2,'BAH'); -- 25
CALL atualizar_gol_partida('PAL',0,0,'FLA'); -- 26
CALL atualizar_gol_partida('CAP',1,0,'INT'); -- 27
CALL atualizar_gol_partida('BOT',5,1,'JUV'); -- 28
CALL atualizar_gol_partida('ACG',0,3,'SAO'); -- 29
CALL atualizar_gol_partida('CRI',1,1,'FOR'); -- 30
CALL atualizar_gol_partida('VAS',0,4,'CRI'); -- 31
CALL atualizar_gol_partida('CUI',0,3,'CAM'); -- 32
CALL atualizar_gol_partida('BAH',1,0,'GRE'); -- 33
CALL atualizar_gol_partida('FLA',0,2,'BOT'); -- 34
CALL atualizar_gol_partida('CRU',3,1,'VIT'); -- 35
CALL atualizar_gol_partida('COR',3,0,'FLU'); -- 36
CALL atualizar_gol_partida('FOR',1,1,'RBB'); -- 37
CALL atualizar_gol_partida('JUV',1,1,'CAP'); -- 38
CALL atualizar_gol_partida('INT',1,1,'ACG'); -- 39
CALL atualizar_gol_partida('SAO',0,0,'PAL'); -- 40
CALL atualizar_gol_partida('FLU',2,2,'CAM'); -- 41
CALL atualizar_gol_partida('RBB',1,1,'FLA'); -- 42
CALL atualizar_gol_partida('COR',0,0,'FOR'); -- 43
CALL atualizar_gol_partida('VIT',1,3,'SAO'); -- 44
CALL atualizar_gol_partida('CAP',1,0,'VAS'); -- 45
CALL atualizar_gol_partida('BOT',1,2,'BAH'); -- 46
CALL atualizar_gol_partida('CUI',0,2,'PAL'); -- 47
CALL atualizar_gol_partida('JUV',1,0,'ACG'); -- 48
CALL atualizar_gol_partida('CRU',0,0,'INT'); -- 49
CALL atualizar_gol_partida('GRE',1,2,'CRI'); -- 50
CALL atualizar_gol_partida('FLA',2,0,'COR'); -- 51
CALL atualizar_gol_partida('PAL',0,2,'CAP'); -- 52
CALL atualizar_gol_partida('FOR',1,1,'BOT'); -- 53
CALL atualizar_gol_partida('ACG',0,1,'CRU'); -- 54
CALL atualizar_gol_partida('BAH',1,0,'RBB'); -- 55
CALL atualizar_gol_partida('VAS',2,1,'VIT'); -- 56
CALL atualizar_gol_partida('SAO',2,1,'FLU'); -- 57
CALL atualizar_gol_partida('CRI',2,5,'CUI'); -- 58
CALL atualizar_gol_partida('INT',2,1,'JUV'); -- 59
CALL atualizar_gol_partida('CAM',2,1,'GRE'); -- 60
CALL atualizar_gol_partida('GRE',0,2,'RBB'); -- 61
CALL atualizar_gol_partida('VIT',0,2,'ACG'); -- 62
CALL atualizar_gol_partida('FLU',1,1,'JUV'); -- 63
CALL atualizar_gol_partida('CUI',0,1,'INT'); -- 64
CALL atualizar_gol_partida('COR',0,1,'BOT'); -- 65
CALL atualizar_gol_partida('CAM',1,1,'BAH'); -- 66
CALL atualizar_gol_partida('VAS',1,6,'FLA'); -- 67
CALL atualizar_gol_partida('CRI',1,2,'PAL'); -- 68
CALL atualizar_gol_partida('SAO',2,0,'CRU'); -- 69
CALL atualizar_gol_partida('FOR',1,0,'CAP'); -- 70
CALL atualizar_gol_partida('ACG',2,2,'COR'); -- 71
CALL atualizar_gol_partida('JUV',1,1,'VIT'); -- 72
CALL atualizar_gol_partida('BOT',1,0,'FLU'); -- 73
CALL atualizar_gol_partida('RBB',1,2,'CAM'); -- 74
CALL atualizar_gol_partida('CRU',2,1,'CUI'); -- 75
CALL atualizar_gol_partida('INT',0,0,'SAO'); -- 76
CALL atualizar_gol_partida('FLA',2,1,'GRE'); -- 77
CALL atualizar_gol_partida('CAP',3,1,'CRI'); -- 78
CALL atualizar_gol_partida('BAH',1,0,'FOR'); -- 79
CALL atualizar_gol_partida('PAL',2,0,'VAS'); -- 80
CALL atualizar_gol_partida('RBB',2,1,'JUV'); -- 81
CALL atualizar_gol_partida('FLU',1,2,'ACG'); -- 82
CALL atualizar_gol_partida('VIT',2,1,'INT'); -- 83
CALL atualizar_gol_partida('COR',2,2,'SAO'); -- 84
CALL atualizar_gol_partida('CAP',1,1,'FLA'); -- 85
CALL atualizar_gol_partida('GRE',1,2,'BOT'); -- 86
CALL atualizar_gol_partida('VAS',0,0,'CRU'); -- 87
CALL atualizar_gol_partida('CUI',5,0,'FOR'); -- 88
CALL atualizar_gol_partida('CRI',2,2,'BAH'); -- 89
CALL atualizar_gol_partida('CAM',0,4,'PAL'); -- 90
CALL atualizar_gol_partida('BOT',1,1,'CAP'); -- 91
CALL atualizar_gol_partida('ACG',1,2,'CRI'); -- 92
CALL atualizar_gol_partida('SAO',0,1,'CUI'); -- 93
CALL atualizar_gol_partida('FOR',1,0,'GRE'); -- 94
CALL atualizar_gol_partida('JUV',2,0,'VAS'); -- 95
CALL atualizar_gol_partida('INT',1,0,'COR'); -- 96
CALL atualizar_gol_partida('CRU',2,0,'FLU'); -- 97
CALL atualizar_gol_partida('VIT',4,2,'CAM'); -- 98
CALL atualizar_gol_partida('FLA',2,1,'BAH'); -- 99
CALL atualizar_gol_partida('PAL',2,1,'RBB'); -- 100
CALL atualizar_gol_partida('CRI',2,1,'BOT'); -- 101
CALL atualizar_gol_partida('GRE',0,1,'INT'); -- 102
CALL atualizar_gol_partida('CUI',0,0,'ACG'); -- 103
CALL atualizar_gol_partida('VAS',4,1,'SAO'); -- 104
CALL atualizar_gol_partida('BAH',4,1,'CRU'); -- 105
CALL atualizar_gol_partida('FLU',0,1,'FLA'); -- 106
CALL atualizar_gol_partida('CAP',1,1,'COR'); -- 107
CALL atualizar_gol_partida('CAM',1,1,'FOR'); -- 108
CALL atualizar_gol_partida('PAL',3,1,'JUV'); -- 109
CALL atualizar_gol_partida('RBB',2,1,'VIT'); -- 110
CALL atualizar_gol_partida('CRU',2,0,'CAP'); -- 111
CALL atualizar_gol_partida('BOT',2,1,'RBB'); -- 112
CALL atualizar_gol_partida('COR',1,1,'CUI'); -- 113
CALL atualizar_gol_partida('ACG',1,1,'GRE'); -- 114
CALL atualizar_gol_partida('JUV',2,1,'FLA'); -- 115
CALL atualizar_gol_partida('INT',1,2,'CAM'); -- 116
CALL atualizar_gol_partida('BAH',2,1,'VAS'); -- 117
CALL atualizar_gol_partida('FOR',3,0,'PAL'); -- 118
CALL atualizar_gol_partida('FLU',0,1,'VIT'); -- 119
CALL atualizar_gol_partida('SAO',2,1,'CRI'); -- 120
CALL atualizar_gol_partida('VAS',1,1,'BOT'); -- 121
CALL atualizar_gol_partida('CUI',1,1,'RBB'); -- 122
CALL atualizar_gol_partida('CAM',1,1,'ACG'); -- 123
CALL atualizar_gol_partida('GRE',1,0,'FLU'); -- 124
CALL atualizar_gol_partida('SAO',3,1,'BAH'); -- 125
CALL atualizar_gol_partida('FOR',2,1,'JUV'); -- 126
CALL atualizar_gol_partida('VIT',0,1,'CAP'); -- 127
CALL atualizar_gol_partida('FLA',2,1,'CRU'); -- 128
CALL atualizar_gol_partida('CRI',1,1,'INT'); -- 129
CALL atualizar_gol_partida('PAL',2,0,'COR'); -- 130
CALL atualizar_gol_partida('CUI',1,2,'BOT'); -- 131
CALL atualizar_gol_partida('VAS',2,0,'FOR'); -- 132
CALL atualizar_gol_partida('CRI',1,0,'CRU'); -- 133
CALL atualizar_gol_partida('CAM',2,4,'FLA'); -- 134
CALL atualizar_gol_partida('RBB',3,1,'ACG'); -- 135
CALL atualizar_gol_partida('CAP',1,2,'SAO'); -- 136
CALL atualizar_gol_partida('GRE',2,2,'PAL'); -- 137
CALL atualizar_gol_partida('BAH',2,0,'JUV'); -- 138
CALL atualizar_gol_partida('FLU',1,1,'INT'); -- 139
CALL atualizar_gol_partida('COR',3,2,'VIT'); -- 140
CALL atualizar_gol_partida('FLA',1,1,'CUI'); -- 141
CALL atualizar_gol_partida('SAO',2,0,'RBB'); -- 142
CALL atualizar_gol_partida('CRU',3,0,'COR'); -- 143
CALL atualizar_gol_partida('FOR',1,0,'FLU'); -- 144
CALL atualizar_gol_partida('JUV',3,0,'GRE'); -- 145
CALL atualizar_gol_partida('INT',1,2,'VAS'); -- 146
CALL atualizar_gol_partida('VIT',2,1,'CRI'); -- 147
CALL atualizar_gol_partida('PAL',2,0,'BAH'); -- 148
CALL atualizar_gol_partida('ACG',1,2,'CAP'); -- 149
CALL atualizar_gol_partida('BOT',3,0,'CAM'); -- 150
CALL atualizar_gol_partida('GRE',0,2,'CRU'); -- 151
CALL atualizar_gol_partida('VAS',2,0,'COR'); -- 152
CALL atualizar_gol_partida('CAP',1,3,'BAH'); -- 153
CALL atualizar_gol_partida('PAL',3,1,'ACG'); -- 154
CALL atualizar_gol_partida('FLA',1,2,'FOR'); -- 155
CALL atualizar_gol_partida('CRI',1,1,'FLU'); -- 156
CALL atualizar_gol_partida('CAM',2,1,'SAO'); -- 157
CALL atualizar_gol_partida('VIT',0,1,'BOT'); -- 158
CALL atualizar_gol_partida('CUI',0,0,'JUV'); -- 159
CALL atualizar_gol_partida('RBB',2,2,'INT'); -- 160
CALL atualizar_gol_partida('CRU',2,1,'RBB'); -- 161
CALL atualizar_gol_partida('BAH',1,2,'CUI'); -- 162
CALL atualizar_gol_partida('JUV',1,1,'CAM'); -- 163
CALL atualizar_gol_partida('COR',2,1,'CRI'); -- 164
CALL atualizar_gol_partida('ACG',0,1,'VAS'); -- 165
CALL atualizar_gol_partida('SAO',1,0,'GRE'); -- 166
CALL atualizar_gol_partida('BOT',1,0,'PAL'); -- 167
CALL atualizar_gol_partida('FOR',3,1,'VIT'); -- 168
CALL atualizar_gol_partida('FLU',1,0,'CAP'); -- 169
CALL atualizar_gol_partida('INT',1,1,'FLA'); -- 170
CALL atualizar_gol_partida('FLA',2,1,'CRI'); -- 171
CALL atualizar_gol_partida('BOT',1,0,'INT'); -- 172
CALL atualizar_gol_partida('PAL',2,0,'CRU'); -- 173
CALL atualizar_gol_partida('GRE',2,0,'VIT'); -- 174
CALL atualizar_gol_partida('CAM',2,0,'VAS'); -- 175
CALL atualizar_gol_partida('BAH',0,1,'COR'); -- 176
CALL atualizar_gol_partida('RBB',1,0,'CAP'); -- 177
CALL atualizar_gol_partida('FOR',3,1,'ACG'); -- 178
CALL atualizar_gol_partida('JUV',0,0,'SAO'); -- 179
CALL atualizar_gol_partida('CUI',0,1,'FLU'); -- 180
CALL atualizar_gol_partida('CRU',2,0,'JUV'); -- 181
CALL atualizar_gol_partida('SAO',2,2,'BOT'); -- 182
CALL atualizar_gol_partida('VIT',1,2,'FLA'); -- 183
CALL atualizar_gol_partida('FLU',1,0,'PAL'); -- 184
CALL atualizar_gol_partida('ACG',1,1,'BAH'); -- 185
CALL atualizar_gol_partida('COR',2,2,'GRE'); -- 186
CALL atualizar_gol_partida('CRI',1,0,'RBB'); -- 187
CALL atualizar_gol_partida('INT',2,1,'FOR'); -- 188
CALL atualizar_gol_partida('VAS',1,0,'CUI'); -- 189
CALL atualizar_gol_partida('CAP',1,0,'CAM'); -- 190
CALL atualizar_gol_partida('PAL',0,2,'VIT'); -- 191
CALL atualizar_gol_partida('JUV',1,2,'CRI'); -- 192
CALL atualizar_gol_partida('BAH',1,1,'INT'); -- 193
CALL atualizar_gol_partida('BOT',0,3,'CRU'); -- 194
CALL atualizar_gol_partida('FOR',1,0,'SAO'); -- 195
CALL atualizar_gol_partida('RBB',0,1,'FLU'); -- 196
CALL atualizar_gol_partida('FLA',2,0,'ACG'); -- 197
CALL atualizar_gol_partida('GRE',1,0,'VAS'); -- 198
CALL atualizar_gol_partida('CAM',2,1,'COR'); -- 199
CALL atualizar_gol_partida('CUI',1,2,'CAP'); -- 200
CALL atualizar_gol_partida('VIT',1,0,'CUI'); -- 201
CALL atualizar_gol_partida('VAS',2,2,'RBB'); -- 202
CALL atualizar_gol_partida('ACG',1,4,'BOT'); -- 203
CALL atualizar_gol_partida('CRI',2,1,'CAM'); -- 204
CALL atualizar_gol_partida('SAO',1,0,'FLA'); -- 205
CALL atualizar_gol_partida('FLU',1,0,'BAH'); -- 206
CALL atualizar_gol_partida('COR',1,1,'JUV'); -- 207
CALL atualizar_gol_partida('CAP',0,2,'GRE'); -- 208
CALL atualizar_gol_partida('INT',1,1,'PAL'); -- 209
CALL atualizar_gol_partida('CRU',1,2,'FOR'); -- 210
CALL atualizar_gol_partida('FOR',1,0,'CRI'); -- 211
CALL atualizar_gol_partida('CUI',1,3,'GRE'); -- 212
CALL atualizar_gol_partida('CRU',0,0,'CAM'); -- 213
CALL atualizar_gol_partida('VAS',2,0,'FLU'); -- 214
CALL atualizar_gol_partida('COR',1,1,'RBB'); -- 215
CALL atualizar_gol_partida('JUV',3,2,'BOT'); -- 216
CALL atualizar_gol_partida('BAH',2,0,'VIT'); -- 217
CALL atualizar_gol_partida('FLA',1,1,'PAL'); -- 218
CALL atualizar_gol_partida('SAO',1,0,'ACG'); -- 219
CALL atualizar_gol_partida('INT',2,2,'CAP'); -- 220
CALL atualizar_gol_partida('GRE',0,2,'BAH'); -- 221
CALL atualizar_gol_partida('CAM',1,1,'CUI'); -- 222
CALL atualizar_gol_partida('RBB',1,2,'FOR'); -- 223
CALL atualizar_gol_partida('FLU',0,0,'COR'); -- 224
CALL atualizar_gol_partida('PAL',2,1,'SAO'); -- 225
CALL atualizar_gol_partida('ACG',1,0,'INT'); -- 226
CALL atualizar_gol_partida('CRI',2,2,'VAS'); -- 227
CALL atualizar_gol_partida('BOT',4,1,'FLA'); -- 228
CALL atualizar_gol_partida('CAP',1,2,'JUV'); -- 229
CALL atualizar_gol_partida('VIT',2,2,'CRU'); -- 230
CALL atualizar_gol_partida('ACG',2,1,'JUV'); -- 231
CALL atualizar_gol_partida('PAL',5,0,'CUI'); -- 232
CALL atualizar_gol_partida('CAM',0,2,'FLU'); -- 233
CALL atualizar_gol_partida('BAH',0,0,'BOT'); -- 234
CALL atualizar_gol_partida('FOR',1,0,'COR'); -- 235
CALL atualizar_gol_partida('CRI',0,1,'GRE'); -- 236
CALL atualizar_gol_partida('SAO',2,1,'VIT'); -- 237
CALL atualizar_gol_partida('INT',1,0,'CRU'); -- 238
CALL atualizar_gol_partida('FLA',2,1,'RBB'); -- 239
CALL atualizar_gol_partida('VAS',2,1,'CAP'); -- 240
CALL atualizar_gol_partida('CUI',2,1,'CRI'); -- 241
CALL atualizar_gol_partida('BOT',2,0,'FOR'); -- 242
CALL atualizar_gol_partida('GRE',2,3,'CAM'); -- 243
CALL atualizar_gol_partida('CRU',3,1,'ACG'); -- 244
CALL atualizar_gol_partida('COR',2,1,'FLA'); -- 245
CALL atualizar_gol_partida('VIT',0,1,'VAS'); -- 246
CALL atualizar_gol_partida('FLU',2,0,'SAO'); -- 247
CALL atualizar_gol_partida('RBB',2,1,'BAH'); -- 248
CALL atualizar_gol_partida('CAP',0,2,'PAL'); -- 249
CALL atualizar_gol_partida('JUV',1,3,'INT'); -- 250
CALL atualizar_gol_partida('ACG',0,2,'VIT'); -- 251
CALL atualizar_gol_partida('CAP',1,1,'FOR'); -- 252
CALL atualizar_gol_partida('BOT',2,1,'COR'); -- 253
CALL atualizar_gol_partida('PAL',5,0,'CRI'); -- 254
CALL atualizar_gol_partida('RBB',2,2,'GRE'); -- 255
CALL atualizar_gol_partida('JUV',2,1,'FLU'); -- 256
CALL atualizar_gol_partida('CRU',0,1,'SAO'); -- 257
CALL atualizar_gol_partida('BAH',3,0,'CAM'); -- 258
CALL atualizar_gol_partida('FLA',1,1,'VAS'); -- 259
CALL atualizar_gol_partida('INT',3,0,'CUI'); -- 260
CALL atualizar_gol_partida('VIT',1,0,'JUV'); -- 261
CALL atualizar_gol_partida('COR',3,0,'ACG'); -- 262
CALL atualizar_gol_partida('FLU',0,1,'BOT'); -- 263
CALL atualizar_gol_partida('FOR',4,1,'BAH'); -- 264
CALL atualizar_gol_partida('CAM',3,0,'RBB'); -- 265
CALL atualizar_gol_partida('VAS',0,1,'PAL'); -- 266
CALL atualizar_gol_partida('GRE',3,2,'FLA'); -- 267
CALL atualizar_gol_partida('SAO',1,3,'INT'); -- 268
CALL atualizar_gol_partida('CUI',0,0,'CRU'); -- 269
CALL atualizar_gol_partida('CRI',0,0,'CAP'); -- 270
CALL atualizar_gol_partida('PAL',2,1,'CAM'); -- 271
CALL atualizar_gol_partida('BOT',0,0,'GRE'); -- 272
CALL atualizar_gol_partida('JUV',1,1,'RBB'); -- 273
CALL atualizar_gol_partida('SAO',3,1,'COR'); -- 274
CALL atualizar_gol_partida('FOR',1,0,'CUI'); -- 275
CALL atualizar_gol_partida('ACG',1,0,'FLU'); -- 276
CALL atualizar_gol_partida('INT',3,1,'VIT'); -- 277
CALL atualizar_gol_partida('CRU',1,1,'VAS'); -- 278
CALL atualizar_gol_partida('BAH',1,0,'CRI'); -- 279
CALL atualizar_gol_partida('FLA',1,0,'CAP'); -- 280
CALL atualizar_gol_partida('CRI',2,0,'ACG'); -- 281
CALL atualizar_gol_partida('FLU',1,0,'CRU'); -- 282
CALL atualizar_gol_partida('GRE',3,1,'FOR'); -- 283
CALL atualizar_gol_partida('CAM',2,2,'VIT'); -- 284
CALL atualizar_gol_partida('RBB',0,0,'PAL'); -- 285
CALL atualizar_gol_partida('CAP',0,1,'BOT'); -- 286
CALL atualizar_gol_partida('BAH',0,2,'FLA'); -- 287
CALL atualizar_gol_partida('COR',2,2,'INT'); -- 288
CALL atualizar_gol_partida('CUI',2,0,'SAO'); -- 289
CALL atualizar_gol_partida('VAS',1,1,'JUV'); -- 290
CALL atualizar_gol_partida('SAO',3,0,'VAS'); -- 291
CALL atualizar_gol_partida('FOR',1,1,'CAM'); -- 292
CALL atualizar_gol_partida('FLA',0,2,'FLU'); -- 293
CALL atualizar_gol_partida('COR',5,2,'CAP'); -- 294
CALL atualizar_gol_partida('ACG',0,0,'CUI'); -- 295
CALL atualizar_gol_partida('BOT',1,1,'CRI'); -- 296
CALL atualizar_gol_partida('CRU',1,1,'BAH'); -- 297
CALL atualizar_gol_partida('INT',1,0,'GRE'); -- 298
CALL atualizar_gol_partida('VIT',1,0,'RBB'); -- 299
CALL atualizar_gol_partida('JUV',3,5,'PAL'); -- 300
CALL atualizar_gol_partida('GRE',3,1,'ACG'); -- 301
CALL atualizar_gol_partida('VIT',2,1,'FLU'); -- 302
CALL atualizar_gol_partida('FLA',4,2,'JUV'); -- 303
CALL atualizar_gol_partida('PAL',2,2,'FOR'); -- 304
CALL atualizar_gol_partida('CAP',3,0,'CRU'); -- 305
CALL atualizar_gol_partida('CAM',1,3,'INT'); -- 306
CALL atualizar_gol_partida('RBB',0,1,'BOT'); -- 307
CALL atualizar_gol_partida('CRI',1,1,'SAO'); -- 308
CALL atualizar_gol_partida('CUI',0,1,'COR'); -- 309
CALL atualizar_gol_partida('VAS',3,2,'BAH'); -- 310
CALL atualizar_gol_partida('FLU',2,2,'GRE'); -- 311
CALL atualizar_gol_partida('RBB',0,0,'CUI'); -- 312
CALL atualizar_gol_partida('CAP',1,2,'VIT'); -- 313
CALL atualizar_gol_partida('JUV',0,3,'FOR'); -- 314
CALL atualizar_gol_partida('COR',2,0,'PAL'); -- 315
CALL atualizar_gol_partida('INT',2,0,'CRI'); -- 316
CALL atualizar_gol_partida('BAH',0,3,'SAO'); -- 317
CALL atualizar_gol_partida('BOT',3,0,'VAS'); -- 318
CALL atualizar_gol_partida('CRU',0,1,'FLA'); -- 319
CALL atualizar_gol_partida('ACG',1,0,'CAM'); -- 320
CALL atualizar_gol_partida('INT',2,0,'FLU'); -- 321
CALL atualizar_gol_partida('PAL',1,0,'GRE'); -- 322
CALL atualizar_gol_partida('VIT',1,2,'COR'); -- 323
CALL atualizar_gol_partida('BOT',0,0,'CUI'); -- 324
CALL atualizar_gol_partida('CRU',2,1,'CRI'); -- 325
CALL atualizar_gol_partida('FOR',3,0,'VAS'); -- 326
CALL atualizar_gol_partida('ACG',0,0,'RBB'); -- 327
CALL atualizar_gol_partida('JUV',2,1,'BAH'); -- 328
CALL atualizar_gol_partida('SAO',2,1,'CAP'); -- 329
CALL atualizar_gol_partida('FLA',0,0,'CAM'); -- 330
CALL atualizar_gol_partida('COR',2,1,'CRU'); -- 331
CALL atualizar_gol_partida('RBB',1,1,'SAO'); -- 332
CALL atualizar_gol_partida('CAP',2,0,'ACG'); -- 333
CALL atualizar_gol_partida('CRI',0,1,'VIT'); -- 334
CALL atualizar_gol_partida('BAH',1,2,'PAL'); -- 335
CALL atualizar_gol_partida('GRE',2,2,'JUV'); -- 336
CALL atualizar_gol_partida('CUI',1,2,'FLA'); -- 337
CALL atualizar_gol_partida('CAM',0,0,'BOT'); -- 338
CALL atualizar_gol_partida('VAS',0,1,'INT'); -- 339
CALL atualizar_gol_partida('FLU',2,2,'FOR'); -- 340
CALL atualizar_gol_partida('BOT',1,1,'VIT'); -- 341
CALL atualizar_gol_partida('ACG',0,1,'PAL'); -- 342
CALL atualizar_gol_partida('JUV',1,1,'CUI'); -- 343
CALL atualizar_gol_partida('SAO',2,2,'CAM'); -- 344
CALL atualizar_gol_partida('INT',4,1,'RBB'); -- 345
CALL atualizar_gol_partida('BAH',1,1,'CAP'); -- 346
CALL atualizar_gol_partida('COR',3,1,'VAS'); -- 347
CALL atualizar_gol_partida('FLU',0,0,'CRI'); -- 348
CALL atualizar_gol_partida('FOR',0,0,'FLA'); -- 349
CALL atualizar_gol_partida('CRU',1,1,'GRE'); -- 350
CALL atualizar_gol_partida('CAM',2,3,'JUV'); -- 351
CALL atualizar_gol_partida('PAL',1,3,'BOT'); -- 352
CALL atualizar_gol_partida('CUI',1,2,'BAH'); -- 353
CALL atualizar_gol_partida('CRI',2,4,'COR'); -- 354
CALL atualizar_gol_partida('VAS',2,2,'ACG'); -- 355
CALL atualizar_gol_partida('GRE',2,1,'SAO'); -- 356
CALL atualizar_gol_partida('FLA',3,2,'INT'); -- 357
CALL atualizar_gol_partida('VIT',2,0,'FOR'); -- 358
CALL atualizar_gol_partida('RBB',1,1,'CRU'); -- 359
CALL atualizar_gol_partida('CAP',1,1,'FLU'); -- 360
CALL atualizar_gol_partida('INT',0,1,'BOT'); -- 361
CALL atualizar_gol_partida('CRU',1,2,'PAL'); -- 362
CALL atualizar_gol_partida('VIT',1,1,'GRE'); -- 363
CALL atualizar_gol_partida('FLU',1,0,'CUI'); -- 364
CALL atualizar_gol_partida('VAS',2,0,'CAM'); -- 365
CALL atualizar_gol_partida('COR',3,0,'BAH'); -- 366
CALL atualizar_gol_partida('SAO',1,2,'JUV'); -- 367
CALL atualizar_gol_partida('CAP',1,2,'RBB'); -- 368
CALL atualizar_gol_partida('ACG',3,1,'FOR'); -- 369
CALL atualizar_gol_partida('CRI',0,3,'FLA'); -- 370
CALL atualizar_gol_partida('GRE',0,3,'COR'); -- 371
CALL atualizar_gol_partida('CAM',1,0,'CAP'); -- 372
CALL atualizar_gol_partida('BAH',2,0,'ACG'); -- 373
CALL atualizar_gol_partida('FLA',2,2,'VIT'); -- 374
CALL atualizar_gol_partida('BOT',2,1,'SAO'); -- 375
CALL atualizar_gol_partida('PAL',0,1,'FLU'); -- 376
CALL atualizar_gol_partida('RBB',5,1,'CRI'); -- 377
CALL atualizar_gol_partida('FOR',3,0,'INT'); -- 378
CALL atualizar_gol_partida('CUI',1,2,'VAS'); -- 379
CALL atualizar_gol_partida('JUV',0,1,'CRU'); -- 380