DROP DATABASE IF EXISTS DB_CAMPEONATO_BRASILEIRO;
CREATE DATABASE DB_CAMPEONATO_BRASILEIRO;
USE DB_CAMPEONATO_BRASILEIRO;

CREATE TABLE SNITB001_ESTADIO (
   ID_ESTADIO  INT NOT NULL AUTO_INCREMENT,
   NO_ESTADIO  VARCHAR(100) NOT NULL,
   ED_ESTADIO  VARCHAR(200) NOT NULL,
   QT_CAPACIDADE  DECIMAL(5,4) NOT NULL,
  CONSTRAINT PK_SNITB001 PRIMARY KEY ( ID_ESTADIO ),
  CONSTRAINT UK01_SNITB001 UNIQUE ( NO_ESTADIO )
  );


CREATE TABLE SNITB002_TIME  (
   ID_TIME  INT NOT NULL AUTO_INCREMENT,
   NO_TIME  VARCHAR(150) NOT NULL,
   NO_CIDADE  VARCHAR(150) NOT NULL,
   NO_ESTADO  VARCHAR(150) NOT NULL,
   DT_CRIACAO  DATE NOT NULL,
   QT_TITULO  INT NULL,
   ID_ESTADIO  INT NOT NULL,
  CONSTRAINT PK_SNITB002 PRIMARY KEY ( ID_TIME ),
  CONSTRAINT UK01_SNITB002 UNIQUE ( NO_TIME ),
  CONSTRAINT FK01_SNITB001_SNITB002 FOREIGN KEY ( ID_ESTADIO )
    REFERENCES SNITB001_ESTADIO ( ID_ESTADIO )
    );


CREATE TABLE SNITB004_PARTIDA  (
   ID_PARTIDA  INT NOT NULL AUTO_INCREMENT,
   NR_RODADA_CAMPEONATO  INT NOT NULL,
   DH_PARTIDA  DATETIME NOT NULL,
   ID_ESTADIO  INT NOT NULL,
   ID_TIME_MANDANTE  INT NOT NULL,
   ID_TIME_VISITANTE  INT NOT NULL,
  CONSTRAINT PK_SNITB004 PRIMARY KEY ( ID_PARTIDA ),
  CONSTRAINT  FK01_SNITB001_SNITB004 FOREIGN KEY ( ID_ESTADIO )
    REFERENCES  SNITB001_ESTADIO ( ID_ESTADIO ),
  CONSTRAINT  FK02_SNITB002_SNITB004 FOREIGN KEY ( ID_TIME_MANDANTE )
    REFERENCES SNITB002_TIME ( ID_TIME ),
  CONSTRAINT  FK03_SNITB002_SNITB004 FOREIGN KEY ( ID_TIME_VISITANTE )
    REFERENCES SNITB002_TIME ( ID_TIME )
    );

CREATE TABLE SNITB003_JOGADOR  (
   ID_JOGADOR  INT NOT NULL AUTO_INCREMENT,
   NO_JOGADOR  VARCHAR(100) NOT NULL,
   DT_NASCIMENTO  DATE NOT NULL,
   NO_POSICAO  VARCHAR(50) NOT NULL,
   NR_CAMISA  INT NOT NULL,
   ID_TIME  INT NOT NULL,
  CONSTRAINT PK_SNITB003 PRIMARY KEY ( ID_JOGADOR ),
  CONSTRAINT UK01_SNITB003 UNIQUE ( NO_JOGADOR ),
  CONSTRAINT  FK01_SNITB002_SNITB003 FOREIGN KEY ( ID_TIME )
    REFERENCES SNITB002_TIME ( ID_TIME )
    );


CREATE TABLE SNITB005_EVENTO  (
   ID_EVENTO  INT NOT NULL AUTO_INCREMENT,
   DS_EVENTO  VARCHAR(150) NOT NULL,
   NR_MINUTO  INT NOT NULL,
   ID_PARTIDA  INT NOT NULL,
   ID_JOGADOR  INT NOT NULL,
  PRIMARY KEY ( ID_EVENTO ),
  CONSTRAINT  FK01_SNITB004_SNITB005 FOREIGN KEY ( ID_PARTIDA )
    REFERENCES SNITB004_PARTIDA  ( ID_PARTIDA ),
  CONSTRAINT  FK02_SNITB003_SNITB005 FOREIGN KEY ( ID_JOGADOR ) 
    REFERENCES  SNITB003_JOGADOR  ( ID_JOGADOR )
    );